version: "3"
services:
  pis-kafka-prod:
    image: jciarka/pis-kafka-cons:latest
    # network_mode: "host" # use host network - enable communicating with internet
    ports:
      - "9091:9091"
    environment:
      - KAFKA_BOOTSTRAP_SERVER=192.168.162.221:9092
      - MONGO_SERVER_ADDRESS=192.168.162.221
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_USERNAME=admin
      - MONGO_SERVER_PASSWORD=password
      - MONGO_SERVER_DATABASE=pis
