apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: pis-kafka-prod
spec:
  selector:
    matchLabels:
      app: pis-kafka-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: pis-kafka-prod
    spec:
      containers:
        - name: pis-kafka-prod
          image: jciarka/pis-kafka-prod:0.0.1
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: pis-kafka-prod-service
spec:
  selector:
    app: pis-kafka-prod
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090